# Generated by Django 4.2.6 on 2024-01-20 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asarlar',
            name='b_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.b_category'),
        ),
    ]
