# Generated by Django 4.2.6 on 2024-01-20 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_asarlar_b_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asarlar',
            name='b_cat',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.b_category'),
        ),
    ]
