# Generated by Django 4.2.6 on 2024-01-20 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_asarlar_b_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asarlar',
            old_name='asar_nomi',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='asarlar',
            name='b_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.b_category'),
        ),
    ]
