# Generated by Django 4.2.6 on 2024-01-20 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_bayt_parse_mano'),
    ]

    operations = [
        migrations.AddField(
            model_name='bayt_parse',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
